## **Soal 2 - Film Bagus 🎥**

Disediakan dataset daftar film beserta rating yang diberikan oleh penonton.
- __*movies.csv*__ : [unduh](./datasets/movies.csv)
- __*ratings.csv*__ : [unduh](./datasets/ratings.csv)

1. Dengan memanfaatkan dataset tersebut, buatlah sebuah file notebook (_.ipynb_) berisi sebuah __content-based filtering recommendation system__ berdasarkan _genre movie_. Kemudian berikan __rekomendasi 5 judul film__ kepada user berikut:

    - Joko sangat menyukai film bergenre animasi & action, terutama film _**Superman vs. The Elite (2012)**_.

2. Dengan memanfaatkan dataset tersebut, buatlah sebuah file notebook (_.ipynb_) berisi sebuah __collaborative filtering recommendation system__, kemudian berikan __rekomendasi 5 judul film__ kepada user berikut:

    - Widodo sangat menyukai film drama komedi, salah satunya bertajuk _**Being Flynn (2012)**_.

✅ _Commit & push source code jawaban soal ini ke __Github__ Anda, buatlah repo dengan nama __Film Bagus__, kemudian lampirkan __url link repo Github__ Anda via email ke lintang@purwadhika.com!_



In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
movies = pd.read_csv('datasets/movies.csv')
ratings = pd.read_csv('datasets/ratings.csv')

In [19]:
movies.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

#### Content-based filtering berdasarkan **genre**

In [20]:
movies["genres"] = movies["genres"].str.replace("|", " ")

In [21]:
cv = CountVectorizer()
cm = cv.fit_transform(movies["genres"])
cm

<10329x24 sparse matrix of type '<class 'numpy.int64'>'
	with 24183 stored elements in Compressed Sparse Row format>

In [23]:
cv = CountVectorizer()
cm = cv.fit_transform(movies["genres"])

# total kata unik di col genres
print(cv.get_feature_names())

# matrix freq tiap kata di tiap data
print(cm.toarray())

['action', 'adventure', 'animation', 'children', 'comedy', 'crime', 'documentary', 'drama', 'fantasy', 'fi', 'film', 'genres', 'horror', 'imax', 'listed', 'musical', 'mystery', 'no', 'noir', 'romance', 'sci', 'thriller', 'war', 'western']
[[0 1 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[0 1 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [24]:
# Cosine similarity dari tiap data di matrix freq
cosScore = cosine_similarity(cm.toarray())
cosScore

array([[1.        , 0.77459667, 0.31622777, ..., 0.4472136 , 0.        ,
        0.        ],
       [0.77459667, 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.31622777, 0.        , 1.        , ..., 0.70710678, 0.        ,
        0.        ],
       ...,
       [0.4472136 , 0.        , 0.70710678, ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [26]:
# Film kesukaan Joko = Superman vs. The Elite (2012)
movies.loc[movies["title"] == "Superman vs. The Elite (2012)"]

movieId                          title            genres
9370    94974  Superman vs. The Elite (2012)  Action Animation

In [33]:
# Joko suka film Superman vs. The Elite (2012) (index = 9370)
Joko = 9370
# daftar seluruh film beserta cos score
similarMovies = list(enumerate(cosScore[Joko]))

In [37]:
# sort berdasarkan similarity
similarMovies = sorted(similarMovies, key = lambda x : x[1], reverse = True)

In [38]:
# prediksi similarity rekomendasi film untuk Joko
similarMovies[:6]

[(6260, 0.9999999999999998),
 (8637, 0.9999999999999998),
 (9370, 0.9999999999999998),
 (9570, 0.9999999999999998),
 (10167, 0.9999999999999998)]

In [62]:
top5_index = np.array(similarMovies[:6])[:, 0]
top5_index = top5_index.astype('int64')
top5_index

array([ 6260,  8637,  9370,  9570, 10167, 10277])

In [65]:
# Top 5 movies recommendation untuk Joko yang suka Superman vs The Elite (2012)
movies.loc[top5_index].drop(9370, axis = 0)

movieId                                              title  \
6260     26913  Street Fighter II: The Animated Movie (Sutorît...   
8637     79274                  Batman: Under the Red Hood (2010)   
9570     99813     Batman: The Dark Knight Returns, Part 2 (2013)   
10167   124867          Justice League: Throne of Atlantis (2015)   
10277   138104           Justice League: Gods and Monsters (2015)   

                 genres  
6260   Action Animation  
8637   Action Animation  
9570   Action Animation  
10167  Action Animation  
10277  Action Animation